### ISSUE TITLE
Document field values don't update in the query view.

### ISSUE THREAD

**Issue by randito** [bububa/MongoHub#2]
When viewing a result set in the query window, if I edit one of the fields of a document, the value does not get saved in the database.

The field acts like you can edit it.  Clicking on it allows you to enter a value.  However, the value does not get written like you'd expect.  

Steps to duplicate:
1.  Select one of the collections in your list.
2.  Click the query button.
3.  From the result set, select a document.
4.  Select a field from that document.
5.  Click on the box for that field.  You get an input field.
6.  Type in something cool.  Hit return.
7.  The value does not get saved into the database.

**Comment by bububa** [comment]
Sorry, this project will not be updated by myself. If you are using mac, please check http://github.com/bububa/MongoHub-Mac
